-- | Advanced API: full shader reflection types + raw compile helpers.
module Spirdo.Wesl.Reflection
  ( -- * Compile-time interface types
    BindingKind(..)
  , StorageAccess(..)
  , StorageFormat(..)
  , Scalar(..)
  , ScalarType(..)
  , Field(..)
  , Ty(..)
  , Binding(..)
  , ShaderStage(..)
  , IOParam(..)
  , StageIO(..)
  , BindingPlan(..)
  , shaderStage
  , Shader(..)
  , SomeShader(..)
  , shaderSpirv
  , shaderInterface
  , shaderPlan
  , shaderStageCached
  , shaderVertexAttributes
  , UniformValue
  , ToUniform(..)
  , uniform
  , packUniform
  , packUniformFrom
  , validateUniformStorable
  , packUniformStorable
  , V2(..)
  , V3(..)
  , V4(..)
  , M2(..)
  , M3(..)
  , M4(..)
  , M3x4(..)
  , M4x3(..)
  , Half(..)
  , stageIO
  , stageInputs
  , stageOutputs
  , vertexInputs
  , vertexOutputs
  , vertexAttributes
  , VertexFormat(..)
  , VertexAttribute(..)
  , pushConstantLayout
  , ShaderInterface(..)
  , OverrideInfo(..)
  , BindingInfo(..)
  , TypeLayout(..)
  , FieldLayout(..)
  , specializableOverrides
  , CompileError(..)
  , Source(..)
  , CachePolicy(..)
  , Option(..)
  , CompileOptions
  , SamplerBindingMode(..)
  , OverrideSpecMode(..)
  , OverrideValue(..)
  , Diagnostic(..)
  , DiagnosticSeverity(..)
  , defaultCompileOptions
  , defaultOptions
  , applyOptions
  , withSpirvVersion
  , withFeatures
  , withOverrides
  , withOverrideSpecMode
  , withSamplerMode
  , withCache
  , withCacheDir
  , withCacheVerbose
  , withTimingVerbose
  , compile
  , compileWith
  , compileWithDiagnostics
  , compileFile
  , compileFileWith
  , compileFileWithDiagnostics
  , wesl
  , weslWith
  , weslBatch
  , weslBatchWith
  ) where

import Spirdo.Wesl.Compiler
import Spirdo.Wesl.Types
